name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > .env
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" > .env
          echo "PORT=${{ secrets.API_KEY }}" > .env

      - name: Install dependencies
        run: npm install
        run: npm install -g pm2

      - name: Run Node.js script
        run: m2 start server/app.js
